# Generated by Django 2.1.7 on 2019-05-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='ipCom',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
