# Generated by Django 2.1.7 on 2019-05-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ponto', '0005_frequencia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_horario',
            name='tolerancia',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Tolerância'),
        ),
    ]
