# Generated by Django 2.1.7 on 2019-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ponto', '0006_config_horario_tolerancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
