# Generated by Django 2.1.7 on 2019-05-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ponto', '0007_justificativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_horario',
            name='nome',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Tipo de horario'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='justificativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_ponto.Justificativa'),
        ),
    ]
